// tableHeader.js
export default  [
    {
        title: '月份',
        key: 'month',
        dataIndex: 'month',
        align: 'center',
        sorter: false,
    },
    {
        title: '日期',
        key: 'date',
        dataIndex: 'date',
        align: 'center',
        sorter: false,
    },
    {
        title: '凭证号码',
        key: 'voucherNumber',
        dataIndex: 'voucherNumber',
        align: 'center',
        sorter: false,
    },
    {
        title: '支持类型',
        key: 'disburseType',
        dataIndex: 'disburseType',
        align: 'center',
        sorter: false,
    },
    {
        title: '明细科目',
        key: 'subsidiaryAccount',
        dataIndex: 'subsidiaryAccount',
        align: 'center',
        sorter: false,
    },
    {
        title: '摘要',
        key: 'summary',
        dataIndex: 'summary',
        align: 'center',
        sorter: false,
    },
    {
        title: '报销人',
        key: 'reimbursementName',
        dataIndex: 'reimbursementName',
        align: 'center',
        sorter: false,
    },
    {
        title: '付款人',
        key: 'payerName',
        dataIndex: 'payerName',
        align: 'center',
        sorter: false,
    },
    {
        title: '复核人',
        key: 'reviewName',
        dataIndex: 'reviewName',
        align: 'center',
        sorter: false,
    },
    {
        title: '抽核人',
        key: 'spotCheckName',
        dataIndex: 'spotCheckName',
        align: 'center',
        sorter: false,
    },
    {
        title: '部门',
        key: 'deptName',
        dataIndex: 'deptName',
        align: 'center',
        sorter: false,
    },
    {
        title: '流入',
        key: 'flowInto',
        dataIndex: 'flowInto',
        align: 'center',
        sorter: false,
    },
    {
        title: '流出',
        key: 'outflow',
        dataIndex: 'outflow',
        align: 'center',
        sorter: false,
    },
    {
        title: '修改时间',
        key: 'updateTime',
        dataIndex: 'updateTime',
        align: 'center',
        sorter: false,
    },
    {
        title: '创建时间',
        key: 'createTime',
        dataIndex: 'createTime',
        align: 'center',
        sorter: false,
    },
];