// 初始选品审核发布列表
export default [
{
    title: '序号',
    dataIndex: 'index',
    key: 'index',
    align: 'center',
    width: 80,
    fixed: 'left',
    resizable: true,
  },
  {
    title: '模板名称',
    dataIndex: 'shopTemplateName',
    key: 'shopTemplateName',
    align: 'center',
    width: 300,
    minWidth: 300,
    resizable: true,
  },
  {
    title: '所属店铺',
    dataIndex: 'simpleName',
    key: 'account',
    align: 'center',
    width: 300,
    minWidth: 300,
    show: true,
    filter: true,
    resizable: true,
  },
  {
    title: "创建人",
    dataIndex: "createUserName",
    key: "createUserName",
    align: 'center',
    width:188,
    minWidth: 188,
    show: true,
    filter: true,
    resizable: true,
  },
  {
    title: '创建时间',
    dataIndex: 'createTime',
    key: 'createTime',
    align: 'center',
    width: 200,
    minWidth: 200,
    show: true,
    filter: true,
    resizable: true,
  },
  {
    title: '状态',
    dataIndex: 'status_name',
    key: 'status',
    align: 'center',
    width: 200,
    minWidth: 200,
    show: true,
    filter: true,
    resizable: true,
  },
  {
    title: '备注',
    dataIndex: 'remark',
    key: 'remark',
    align: 'center',
    minWidth: 500,
    width: 500,
    show: true,
    filter: true,
    resizable: true,
  },
]
