export const columns = [
  {
    title: "Transaction Date",
    dataIndex: "transactionDate",
    key: "transactionDate",
    width: 180,
  },
  {
    title: "Transaction Type",
    dataIndex: "transactionType",
    key: "transactionType",
    width: 180,
  },
  {
    title: "Fee Name",
    dataIndex: "feeName",
    key: "feeName",
    width: 180,
  },
  {
    title: "Transaction Number",
    dataIndex: "transactionNumber",
    key: "transactionNumber",
    width: 180,
  },
  {
    title: "Details",
    dataIndex: "details",
    key: "details",
    width: 300,
  },
  {
    title: "Seller SKU",
    dataIndex: "sellerSku",
    key: "sellerSku",
    width: 180,
  },
  {
    title: "Lazada SKU",
    dataIndex: "lazadaSku",
    key: "lazadaSku",
    width: 180,
  },
  {
    title: "Amount",
    dataIndex: "amount",
    key: "amount",
    width: 180,
  },
  {
    title: "VAT in Amount",
    dataIndex: "vatinAmount",
    key: "vatinAmount",
    width: 180,
  },
  {
    title: "WHT Amount",
    dataIndex: "whtamount",
    key: "whtamount",
    width: 180,
  },
  {
    title: "WHT included in Amount",
    dataIndex: "whtincludedInAmount",
    key: "whtincludedInAmount",
    width: 210,
  },
  {
    title: "Statement",
    dataIndex: "statement",
    key: "statement",
    width: 180,
  },
  {
    title: "Paid Status",
    dataIndex: "paidStatus",
    key: "paidStatus",
    width: 180,
  },
  {
    title: "Order No.",
    dataIndex: "orderNo",
    key: "orderNo",
    width: 180,
  },
  {
    title: "Order Item No.",
    dataIndex: "orderItemNo",
    key: "orderItemNo",
    width: 180,
  },
  {
    title: "Order Item Status",
    dataIndex: "orderItemStatus",
    key: "orderItemStatus",
    width: 180,
  },
  {
    title: "Shipping Provider",
    dataIndex: "shippingProvider",
    key: "shippingProvider",
    width: 180,
  },
  {
    title: "Shipping Speed",
    dataIndex: "shippingSpeed",
    key: "shippingSpeed",
    width: 180,
  },
  {
    title: "Shipment Type",
    dataIndex: "shipmentType",
    key: "shipmentType",
    width: 180,
  },
  {
    title: "Reference",
    dataIndex: "reference",
    key: "reference",
    width: 180,
  },
  {
    title: "Comment",
    dataIndex: "comment",
    key: "comment",
    width: 180,
  },
  {
    title: "PaymentRefId",
    dataIndex: "paymentRefId",
    key: "paymentRefId",
    width: 180,
  },
];
