/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Access: typeof import('./../src/components/access/index.vue')['default']
    Adjust: typeof import('./../src/components/process-pictures/component/adjust/index.vue')['default']
    BaseLoading: typeof import('./../src/components/base-loading/index.vue')['default']
    CarbonLanguage: typeof import('./../src/components/icons/carbon-language.vue')['default']
    CarbonMoon: typeof import('./../src/components/icons/carbon-moon.vue')['default']
    CarbonSun: typeof import('./../src/components/icons/carbon-sun.vue')['default']
    ChaseSpin: typeof import('./../src/components/base-loading/spin/chase-spin.vue')['default']
    ColorTemplate: typeof import('./../src/components/process-pictures/component/adjust/color-template.vue')['default']
    CroppingTemplate: typeof import('./../src/components/process-pictures/component/adjust/cropping-template.vue')['default']
    CubeSpin: typeof import('./../src/components/base-loading/spin/cube-spin.vue')['default']
    DotSpin: typeof import('./../src/components/base-loading/spin/dot-spin.vue')['default']
    Draw: typeof import('./../src/components/process-pictures/component/draw/index.vue')['default']
    DropdownOfImage: typeof import('./../src/components/dropdown-of-image/index.vue')['default']
    DropdownOfVideo: typeof import('./../src/components/dropdown-of-video/index.vue')['default']
    EliminateTemplate: typeof import('./../src/components/process-pictures/component/adjust/eliminate-template.vue')['default']
    FooterLinks: typeof import('./../src/components/footer-links.vue')['default']
    FooterToolBar: typeof import('./../src/components/footer-tool-bar/index.vue')['default']
    Frame: typeof import('./../src/components/process-pictures/component/frame/index.vue')['default']
    Mark: typeof import('./../src/components/process-pictures/component/mark/index.vue')['default']
    Material: typeof import('./../src/components/process-pictures/component/material/index.vue')['default']
    PageContainer: typeof import('./../src/components/page-container/index.vue')['default']
    Painting: typeof import('./../src/components/process-pictures/component/painting/index.vue')['default']
    PlaneSpin: typeof import('./../src/components/base-loading/spin/plane-spin.vue')['default']
    PreloaderSpin: typeof import('./../src/components/base-loading/spin/preloader-spin.vue')['default']
    ProcessPictures: typeof import('./../src/components/process-pictures/index.vue')['default']
    PulseSpin: typeof import('./../src/components/base-loading/spin/pulse-spin.vue')['default']
    QuillEditor: typeof import('./../src/components/quill-editor/index.vue')['default']
    RectSpin: typeof import('./../src/components/base-loading/spin/rect-spin.vue')['default']
    ResizeTemplate: typeof import('./../src/components/process-pictures/component/adjust/resize-template.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchContentInput: typeof import('./../src/components/search-content-input/index.vue')['default']
    SelectLang: typeof import('./../src/components/select-lang/index.vue')['default']
    Text: typeof import('./../src/components/process-pictures/component/text/index.vue')['default']
    TiledSelect: typeof import('./../src/components/tiled-select/index.vue')['default']
    TiledSelectSort: typeof import('./../src/components/tiled-select-sort/index.vue')['default']
    TokenProvider: typeof import('./../src/components/token-provider/index.vue')['default']
    UserAvatar: typeof import('./../src/components/user-avatar/index.vue')['default']
    VirtualList: typeof import('./../src/components/virtual-list/index.vue')['default']
  }
}
