export const columns = [
  {
    title: "操作",
    dataIndex: "action",
    key: "action",
    slot: "action",
    align: "center",
    sorter: false,
    show: true,
    width: 130,
  },
  {
    title: "主图",
    dataIndex: "artMainImage",
    key: "artMainImage",
    slot: "artMainImage",
    align: "center",
    sorter: false,
    width: 120,
  },
  {
    title: "开发理由",
    dataIndex: "devAccount",
    key: "devAccount",
    slot: "devAccount",
    align: "center",
    sorter: false,
    width: 120,
  },
  {
    title: "市场方向",
    dataIndex: "devAttributableMarket",
    key: "devAttributableMarket",
    slot: "devAttributableMarket",
    sortField: "dev_attributable_market", // 排序字段
    align: "center",
    sorter: true,
    width: 120,
  },
  {
    title: "产品SKU",
    dataIndex: "skuList",
    key: "skuList",
    slot: "skuList",
    align: "center",
    sortField: "sku_list", // 排序字段
    sorter: true,
    width: 120,
  },
  {
    title: "同款产品",
    dataIndex: "meansRelated",
    key: "meansRelated",
    slot: "meansRelated",
    sorter: true,
    sortField: "means_related", // 排序字段
    align: "center",
    width: 140,
  },
  {
    title: "产品名称",
    dataIndex: "tradeName",
    key: "tradeName",
    sorter: true,
    sortField: "trade_name", // 排序字段
    align: "center",
    width: 320,
  },
  {
    title: "状态",
    dataIndex: "status",
    key: "status",
    slot: "status",
    sortField: "status", // 排序字段
    align: "center",
    sorter: true,
    width: 140,
  },
  {
    title: "重量",
    dataIndex: "skuWeight",
    key: "skuWeight",
    align: "center",
    sortField: "sku_weight",
    sorter: true,
    width: 140,
  },
  {
    title: "30天销量",
    dataIndex: "sellCount",
    key: "sellCount",
    align: "center",
    sortField: "sell_count",
    sorter: true,
    width: 140,
  },
  {
    title: "仓储类别",
    dataIndex: "meansKeepGrain",
    key: "meansKeepGrain",
    slot: "meansKeepGrain",
    sortField: "means_keep_grain", // 排序字段
    align: "center",
    sorter: true,
    width: 180,
  },
  {
    title: "分类",
    dataIndex: "classify",
    key: "classify",
    slot: "classify",
    align: "center",
    sortField: "classify", // 排序字段
    sorter: true,
    width: 240,
  },
  {
    title: "审核时间",
    dataIndex: "meansAuditTime",
    key: "means_audit_time",
    sortField: "classify", // 排序字段
    align: "center",
    sorter: true,
    width: 180,
  },
  {
    title: "完成时间",
    dataIndex: "completeTime",
    key: "completeTime",
    align: "center",
    dataIndex: "completeTime",
    sortField: "complete_time",
    sorter: true,
    width: 180,
  },
  {
    title: "仓储选品时间",
    dataIndex: "phSelectionTime",
    key: "phSelectionTime",
    slot: "phSelectionTime",
    align: "center",
    sorter: false,
    width: 180,
  },
  {
    title: "禁止刊登平台",
    dataIndex: "devProhibitPlatform",
    key: "devProhibitPlatform",
    slot: "devProhibitPlatform",
    align: "center",
    sortField: "dev_prohibit_platform",
    sorter: true,
    width: 210,
  },
  {
    title: "侵权类型",
    dataIndex: "tortType",
    key: "tortType",
    slot: "tortType",
    align: "center",
    sortField: "tort_type",
    sorter: true,
    width: 210,
  },
  {
    title: "禁售属性",
    dataIndex: "meansForbidAttribute",
    key: "meansForbidAttribute",
    slot: "meansForbidAttribute",
    sortField: "tort_tmeans_forbid_attributeype",
    sorter: true,
    width: 240,
    align: "center",
  },
  {
    title: "禁售站点",
    dataIndex: "meansForbidSite",
    key: "meansForbidSite",
    slot: "meansForbidSite",
    sortField: "means_forbid_site",
    sorter: true,
    width: 180,
    align: "center",
  },
  {
    title: "美工人员",
    dataIndex: "artPerson",
    key: "artPerson",
    sorter: false,
    width: 100,
    align: "center",
  },
  {
    title: "编辑人员",
    dataIndex: "meansEditPerson",
    key: "meansEditPerson",
    sorter: true,
    sortField: "means_edit_person",
    width: 100,
    align: "center",
  },
  {
    title: "开发人员",
    dataIndex: "developPerson",
    key: "developPerson",
    sorter: true,
    sortField: "develop_person",
    width: 100,
    align: "center",
  },
  {
    title: "部门",
    dataIndex: "developDept",
    key: "developDept",
    sorter: true,
    sortField: "develop_dept",
    width: 120,
    align: "center",
  },
  {
    title: "备注",
    dataIndex: "meansRemark",
    key: "meansRemark",
    slot: "meansRemark",
    sortField: "means_remark",
    width: 120,
    sorter: true,
    align: "center",
  },
  {
    title: "商品ID",
    dataIndex: "commodityId",
    key: "commodityId",
    sorter: false,
    width: 120,
    align: "center",
  },
];
