export default [
  {
    title: '标题/产品ID',
    dataIndex: 'name',
    align: "left",
    width: 380,
    filter: false,
  },
  {
    title: 'SKU信息',
    dataIndex: 'sku',
    align: "center",
    width: 200,
  },
  {
    title: '7/14/30天销量',
    dataIndex: 'saleNum',
    align: "center",
    width: 160,
  },
  {
    title: '售价',
    dataIndex: 'price',
    align: "right",
    sorter: true,
    width: 160,
  },
  {
    title: '原价',
    dataIndex: 'oldPrice',
    align: "right",
    width: 140,
  },
  {
    title: '最低价',
    dataIndex: 'minPrice',
    align: "right",
    width: 140,
  },
  {
    title: '总库存',
    dataIndex: 'stock',
    sorter: true,
    align: "right",
    width: 120,
  },
  {
    title: '错误信息',
    dataIndex: 'errorInfo',
    align: "center",
    width: 200,
  },
  {
    title: '状态',
    dataIndex: 'state', // state
    align: "center",
    width: 120,
    filter: false,
  },
  {
    title: '创建时间',
    dataIndex: 'create_time',
    align: "center",
    sorter: true,
    width: 160,
    filter: false,
  },
  {
    title: '更新时间',
    dataIndex: 'update_time',
    align: "center",
    sorter: true,
    width: 160,
    filter: false,
  },
  {
    title: '操作',
    dataIndex: 'option',
    align: "left",
    width: 140,
    filter: false,
  },
]
