export const columns = [
  {
    title: "店铺ID",
    dataIndex: "sellerId",
    key: "sellerId",
    width: 120,
  },
  {
    title: "订单ID",
    dataIndex: "orderId",
    key: "orderId",
    width: 120,
  },
  {
    title: "商品订单ID",
    dataIndex: "orderItemId",
    key: "orderItemId",
    slot: "orderItemId",
    width: 120,
  },
  {
    title: "订单状态",
    dataIndex: "status",
    key: "status",
    width: 120,
  },
  {
    title: "SKU",
    dataIndex: "sku",
    key: "sku",
    width: 120,
  },
  {
    title: "付款方式",
    dataIndex: "paymentMethod",
    key: "paymentMethod",
    width: 120,
  },
  {
    title: "优惠券",
    dataIndex: "voucher",
    key: "voucher",
    width: 120,
  },
  {
    title: "Tax Amount",
    dataIndex: "taxAmount",
    key: "taxAmount",
    slot: "taxAmount",
    width: 120,
  },
  {
    title: "Voucher Seller",
    dataIndex: "voucherSeller",
    key: "voucherSeller",
    slot: "voucherSeller",
    width: 120,
  },
  {
    title: "Paid Price",
    dataIndex: "paidPrice",
    key: "paidPrice",
    slot: "paidPrice",
    width: 120,
  },
  {
    title: "Supply Price",
    dataIndex: "supplyPrice",
    key: "supplyPrice",
    slot: "supplyPrice",
    width: 120,
  },
  {
    title: "Voucher Seller Lpi",
    dataIndex: "voucherSellerLpi",
    key: "voucherSellerLpi",
    slot: "voucherSellerLpi",
    width: 160,
  },
  {
    title: "Wallet Credits",
    dataIndex: "walletCredits",
    key: "walletCredits",
    slot: "walletCredits",
    width: 160,
  },
  {
    title: "Currency",
    dataIndex: "currency",
    key: "currency",
    slot: "currency",
    width: 160,
  },
  {
    title: "Shipping Provider Type",
    dataIndex: "shippingProviderType",
    key: "shippingProviderType",
    slot: "shippingProviderType",
    width: 180,
  },
  {
    title: "Voucher Platform Lpi",
    dataIndex: "voucherPlatformLpi",
    key: "voucherPlatformLpi",
    slot: "voucherPlatformLpi",
    width: 180,
  },
  {
    title: "Shipping Fee Original",
    dataIndex: "shippingFeeOriginal",
    key: "shippingFeeOriginal",
    slot: "shippingFeeOriginal",
    width: 180,
  },
  {
    title: "Item Price",
    dataIndex: "itemPrice",
    key: "itemPrice",
    slot: "itemPrice",
    width: 180,
  },
  {
    title: "Is Digital",
    dataIndex: "isDigital",
    key: "isDigital",
    slot: "isDigital",
    width: 180,
  },
  {
    title: "Shipping Service Cost",
    dataIndex: "shippingServiceCost",
    key: "shippingServiceCost",
    width: 180,
  },
  {
    title: "Shipping Fee Discount Seller",
    dataIndex: "shippingFeeDiscountSeller",
    key: "shippingFeeDiscountSeller",
    slot: "shippingFeeDiscountSeller",
    width: 220,
  },
  {
    title: "Shipping Amount",
    dataIndex: "shippingAmount",
    key: "shippingAmount",
    slot: "shippingAmount",
    width: 180,
  },
  {
    title: "Return Status",
    dataIndex: "returnStatus",
    key: "returnStatus",
    slot: "returnStatus",
    width: 180,
  },
  {
    title: "Semi Managed",
    dataIndex: "semiManaged",
    key: "semiManaged",
    slot: "semiManaged",
    width: 180,
  },
  {
    title: "Voucher Amount",
    dataIndex: "voucherAmount",
    key: "voucherAmount",
    slot: "voucherAmount",
    width: 150,
  },
  {
    title: "Supply Price Currency",
    dataIndex: "supplyPriceCurrency",
    key: "supplyPriceCurrency",
    slot: "supplyPriceCurrency",
    width: 180,
  },
  {
    title: "创建时间",
    dataIndex: "createdAt",
    key: "createdAt",
    width: 180,
  },
  {
    title: "更新时间",
    dataIndex: "updatedAt",
    key: "updatedAt",
    width: 180,
  },
];
