export const parentHead = [
  {
    title: '状态',
    dataIndex: 'type',
    key: 'type',
    align:"center",
    sortable:false,
    show: true,
    width: 200,
    filter:false,
  },
  {
    title: '商品详情',
    dataIndex: 'info',
    key: 'info',
    align:"center",
    sortable:false,
    show:true,
    // width:'380',
    filter:false,
  },
  // {
  //   title: 'SKU信息',
  //   dataIndex: 'sku',
  //   key: 'platform',
  //   align:"center",
  //   sortable:false,
  //   width:'280',
  //   show:true,
  //   filter:false,
  // },
  // {
  //   title: '库存/价格',
  //   dataIndex: 'price',
  //   key: 'price',
  //   align:"center",
  //   sortable:false,
  //   // width:'280',
  //   show:true,
  //   filter:false,
  // },
  // {
  //   title: '操作',
  //   dataIndex: 'options',
  //   key: 'options',
  //   align:"center",
  //   sortable:false,
  //   width:'280',
  //   show:true,
  //   filter:false,
  // }
];
export const childHead = [
  {
    title: '图片/标题',
    dataIndex: 'info',
    key: 'info',
    align:"center",
    sortable:false,
    show:true,
    width:500,
    filter:false,
  },
  // {2
  //   title: 'SKU信息',
  //   dataIndex: 'sku',
  //   key: 'platform',
  //   align:"center",
  //   sortable:false,
  //   width:'280',
  //   show:true,
  //   filter:false,
  // },
  {
    title: '状态',
    dataIndex: 'state',
    key: 'state',
    align:"center",
    sortable:false,
    show:true,
    filter:false,
  },
  {
    title: '库存',
    dataIndex: 'quality',
    key: 'quality',
    align:"center",
    sortable:false,
    width:'280',
    show:true,
    filter:false,
  },
  {
    title: '价格',
    dataIndex: 'ourPrice',
    key: 'ourPrice',
    align:"center",
    sortable:false,
    width:'280',
    show:true,
    filter:false,
  },
  {
    title: '操作',
    dataIndex: 'options',
    key: 'options',
    align:"center",
    sortable:false,
    width:'280',
    show:true,
    filter:false,
  }
]