export default [
    {
      title: '产品标题',
      dataIndex: 'description',
      key: 'description',
      align:"center",
      sortable:false,
      show:true,
      width:'380',
      filter:false,
    },
    {
      title: 'SKU',
      dataIndex: 'sku',
      key: 'sku',
      align:"center",
      sortable:false,
      width:'280',
      show:true,
      filter:false,
    },
    {
      title: '销售订单数',
      dataIndex: 'salesOrderNumber',
      key: 'salesOrderNumber',
      align:"center",
      sortable:false,
      show:true,
      filter:false,
    },
    {
      title: '销售数量',
      dataIndex: 'quantityShipped',
      key: 'quantityShipped',
      align:"center",
      sortable:false,
      width:'280',
      show:true,
      filter:false,
    },
    ,
    {
      title: '销售额',
      dataIndex: 'totalAmount',
      key: 'totalAmount',
      align:"center",
      sortable:false,
      width:'280',
      show:true,
      filter:false,
    },
    ,
    {
      title: '退款订单数',
      dataIndex: 'refundOrderNumber',
      key: 'refundOrderNumber',
      align:"center",
      sortable:false,
      width:'280',
      show:true,
      filter:false,
    },
    ,
    {
      title: '退款数量',
      dataIndex: 'fefundQuantity',
      key: 'fefundQuantity',
      align:"center",
      sortable:false,
      width:'280',
      show:true,
      filter:false,
    },
    ,
    {
      title: '退款金额',
      dataIndex: 'refundAmount',
      key: 'refundAmount',
      align:"center",
      sortable:false,
      width:'280',
      show:true,
      filter:false,
    }
  ]