export default [
  {
    label: '账号Code',
    prop: 'account',
    sortable:true,
    show:true,
    width: 300,
    filter:false,
  },
  {
    label: '品类',
    prop: 'classify',
    sortable:false,
    show:true,
    width:"220",
    filter:false,
  },
  {
    label: '禁售属性',
    prop: 'forbidSale',
    sortable:false,
    show:true,
    width:"260",
    filter:false,
  },
  {
    label: '是否自动刊登',
    prop: 'autoPublish',
    sortable:false,
    show:true,
    width: 160,
    filter:false,
  },
  {
    label: '简称',
    prop: 'simpleName',
    sortable:false,
    show:true,
    filter:false,
    width: 330
  },
  {
    label: '仓库',
    prop: 'store',
    sortable:false,
    show:true,
    width: 300,
    filter:false,
  },
  {
    label: '别名',
    prop: 'alias',
    sortable:false,
    show:true,
    filter:false,
    width: 300
  },
  {
    label: '备注',
    prop: 'remark',
    sortable:false,
    show:true,
    width: 330,
    filter:false
  },
  {
    label: '修改时间',
    prop: 'updateTime',
    sortable:true,
    show:true,
    width: 260,
    filter:false,
  },
  {
    label: '创建时间',
    prop: 'createTime',
    sortable:true,
    show:true,
    filter:false,
  },
]
