export default [
    {
      label: "图片",
      prop: "sellerId",
      sortable: false,
      show: true,
      filter: false,
    },
    {
      label: "产品标题",
      prop: "orderId",
      sortable: false,
      show: true,
      filter: false,
    },
    {
      label: "SKU",
      prop: "orderItemId",
      sortable: false,
      show: true,
      filter: false,
    },
    {
      label: "售价",
      prop: "status",
      sortable: false,
      show: true,
      filter: false,
    },
    {
      label: "促销折扣",
      prop: "createdAt",
      sortable: true,
      show: true,
      filter: false,
    },
    {
      label: "促销价格",
      prop: "updatedAt",
      sortable: true,
      show: true,
      filter: false,
    },
    {
      label: "参与其他促销活动",
      prop: "otherPorm",
      sortable: true,
      show: true,
      filter: false,
    },
    {
      label: "促销库存",
      prop: "updatedAt",
      sortable: true,
      show: true,
      filter: false,
    },
    {
      label: "库存",
      prop: "updatedAt",
      sortable: true,
      show: true,
      filter: false,
    },
    {
      label: "操作",
      prop: "option",
      sortable: false,
      show: true,
      width: "100",
      filter: false,
    },
  ];
  