export const header = [
  {
    title: "序号",
    dataIndex: "rowIndex",
    key: "rowIndex",
    slot: "rowIndex",
    align: "center",
    sorter: false,
    width: 60,
  },
  {
    title: "示意图",
    dataIndex: "mainImage",
    key: "mainImage",
    slot: "mainImage",
    align: "center",
    sorter: false,
    width: 80,
  },
  {
    title: "产品标题",
    dataIndex: "productName",
    key: "productName",
    slot: "productName",
    sortField: "dev_attributable_market", // 排序字段
    align: "center",
    sorter: false,
    width: 150,
  },
  {
    title: "SKU",
    dataIndex: "skuList",
    key: "skuList",
    slot: "skuList",
    align: "center",
    sortField: "sku_list", // 排序字段
    sorter: false,
    width: 200,
  },
  {
    title: "平均成本价",
    dataIndex: "averagePrice",
    key: "averagePrice",
    slot: "averagePrice",
    sorter: false,
    sortField: "means_related", // 排序字段
    align: "center",
    width: 80,
  },
  {
    title: "平均重量",
    dataIndex: "averageWeight",
    key: "averageWeight",
    sorter: false,
    sortField: "trade_name", // 排序字段
    align: "center",
    width: 80,
  },
  {
    title: "分类",
    dataIndex: "categoryId",
    key: "categoryId",
    slot: "categoryId",
    align: "center",
    sortField: "classify", // 排序字段
    sorter: false,
    width: 200,
  },
  {
    title: "提交人",
    dataIndex: "selectUserName",
    key: "selectUserName",
    sortField: "selectUserName", // 排序字段
    align: "center",
    sorter: false,
    width: 80,
  },
  {
    title: "提交时间",
    dataIndex: "selectTime",
    key: "selectTime",
    align: "center",
    dataIndex: "selectTime",
    sortField: "complete_time",
    sorter: false,
    width: 100,
  },
  {
    title: "审核人",
    dataIndex: "lastAuditUserName",
    key: "lastAuditUserName",
    slot: "lastAuditUserName",
    align: "center",
    sorter: false,
    width: 80,
  },
  {
    title: "完成时间",
    dataIndex: "lastAuditTime",
    key: "lastAuditTime",
    slot: "lastAuditTime",
    align: "center",
    sortField: "dev_prohibit_platform",
    sorter: false,
    width: 100,
  },
  {
    title: "备注",
    dataIndex: "remark",
    key: "remark",
    slot: "remark",
    sortField: "means_remark",
    width: 120,
    sorter: false,
    align: "center",
  },
]